### ISSUE TITLE
Exception calling "ReadKey" with "1"

### ISSUE THREAD

**Issue by walkercz** [brianlala/AutoSPSourceBuilder#1]
Enhance request:

Running script in ISE cause exception.

You can't using this method in Powershell ISE host by design.

http://connect.microsoft.com/PowerShell/feedback/details/713218/host-ui-rawui-readkey-not-implemented-in-version-3-ctp2

**Comment by brianlala** [comment]
Yup, known issue with the ISE. Just run it in a regular PowerShell window.

Brian
