### ISSUE TITLE
NotImplementedException after the final "Press any key to exit..." in PowerShell ISE

### ISSUE THREAD

**Issue by egor-yudkin** [brianlala/AutoSPSourceBuilder#102]
Running the script on Windows Server 2019 in PowerShell ISE.
The script executes with no issues, but at the end after it prints "Press any key to exit..." instead of waiting for input, it throws an error.

Exception calling "ReadKey" with "1" argument(s): "The method or operation is not implemented."
At line:1 char:1
+ $host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : NotImplementedException

I think it's related to the PowerShell host and in regular PowerShell console it works just fine.
I don't know what's the reason of using $host.UI.RawUI.ReadKey() instead of Read-Host, but maybe you can add additional check for the $host.Name before calling this .ReadKey() method?

**Comment by brianlala** [comment]
a) Don't run this in ISE, which is basically deprecated anyhow
b) Check out the new -Unattended switch to see if it resolves this

**Comment by egor-yudkin** [comment]
> a) Don't run this in ISE, which is basically deprecated anyhow 
Point taken. But I still like to use a dev/test tool that's readily available in any Windows Server out of the box.
> b) Check out the new -Unattended switch to see if it resolves this
Updated the script, tried it again - same error

**Comment by brianlala** [comment]
Did you use the -Unattended switch?

**Comment by egor-yudkin** [comment]
Ah, how did I miss that?!
Now with "-Unattended" switch it doesn't throw an error. Thanks!
