### ISSUE TITLE
Parameters

### ISSUE THREAD

**Issue by Yumonk** [brianlala/AutoSPSourceBuilder#12]
What are the input parameters for running this ?  I only have the following so far
.\AutoSPSourceBuilder.ps1 -Destination "C:\SP" -GetPrerequisites $true

**Comment by brianlala** [comment]
Have you tried 

> Get-Help .\AutoSPSourceBuilder.ps1 -Full

 ?

**Comment by Yumonk** [comment]
Got it.  I had not looked into it.  Thanks for pointing it out.
