### ISSUE TITLE
Is it possible to avoid loading language packs?

### ISSUE THREAD

**Issue by shurick81** [brianlala/AutoSPSourceBuilder#17]
It would be great to be able to use this tool for downloading only cumulative updates without language packs.
Sample use case:
I am installing SharePoint 2013 for only English speaking users, so I use SharePoint 2013 slipstreamed media with SP1. What I need from AutoSPSourceBuilder is downloading the latest CU.

I need this installation media unattended but when I run
`AutoSPSourceBuilder.ps1 -SourceLocation H: -Destination d:\Install\SPMedia -CumulativeUpdate "June 2017"`
it requests me what language pack I would like to download.

**Comment by brianlala** [comment]
Yes, simply hit "Cancel" on the selection UI that appears:

![image](https://user-images.githubusercontent.com/12145177/30212303-5d19880c-9472-11e7-959b-588c87ba429c.png)

Brian

**Comment by shurick81** [comment]
Thank you but this is not exactly "unattended". I am going to run AutoSPSourceBuilder in DSC resource.

**Comment by brianlala** [comment]
Ah, OK. Well AutoSPSourceBuilder wasn't actually intended to be an "unattended" tool, but if you're already comfortable with DSC resources then making the required tweaks to AutoSPSourceBuilder should be fairly easy. Let me know if you still need help.

**Comment by brianlala** [comment]
I actually changed my mind about this - I'm working on some changes, most notably a new switch called -PromptForLanguages which, if omitted, will do exactly what you're asking for: bypass the prompt for languages. It will also add support for only downloading updates - no source media required if you don't want to slipstream.

**Comment by shurick81** [comment]
Ah, I see, that is a good idea. It can be even the other way around, something like "SkipPromptForLanguages". It might be better in case when user wants to use GUI so they they don't have to add more parameters. But of course, one may think of some disadvantages of this inversion. Anyway, it would be great to see this improvement, I'm looking forward to starting using the one.

**Comment by brianlala** [comment]
Those changes are live now BTW. I'm not sure if one switch is better than the other, let me think about it.

Brian

**Comment by shurick81** [comment]
BTW don't you mind if I use your product in SPConfStructor? Do I have to put some reference on your project or personal profile?

**Comment by brianlala** [comment]
Can you tell me what your project is about? Is it open-source as well?

**Comment by shurick81** [comment]
It is about effortless deploying SP on prem dev environment and additionally it allows to quickly start using DSC configuration. Here is the demo about deploying dev environment: https://www.youtube.com/watch?v=QX7Nw5kD7T8&t=1s.
And yes, it is open source.

**Comment by brianlala** [comment]
Looks good, sure just a reference/credit wherever it makes sense.

thanks,
Brian
