### ISSUE TITLE
Hard coded 2010 folder in switches  $env:SystemDrive+"\SP\2010"

### ISSUE THREAD

**Issue by jonimattila** [brianlala/AutoSPSourceBuilder#18]
There is in switches 2010 folder hard coded, after changing manually to 2016 it managed to download prerequisites:

    [Parameter(Mandatory=$false)][ValidateNotNullOrEmpty()]
    [String]$Destination = $env:SystemDrive+"\SP\2010",

**Comment by brianlala** [comment]
It's only set if we omit the -Destination switch. You can and should specify your destination. Agree it's not ideal but it's an easy workaround.

**Comment by brianlala** [comment]
This should now be resolved.
