### ISSUE TITLE
Cannot find path '...\PrerequisiteInstallerFiles' because it does not exist

### ISSUE THREAD

**Issue by Patrikbrann** [brianlala/AutoSPSourceBuilder#19]
Hi,

Can't solve this issue and honestly I cannot see if this is a issue on my end or not.
If i run the script, specifying the -Destination or not, I always get the same error:

> Start-BitsTransfer : Cannot find path 'C:\SP\2016\SharePoint\PrerequisiteInstallerFiles' because it does not exist.
At C:\SPAuto\AutoSPSourceBuilder.ps1:132 char:20
$job = Start-BitsTransfer -Asynchronous -Source $url -Destinatio ...
CategoryInfo: ObjectNotFound: (C:\SP\2016\Shar...eInstallerFiles:String) [Start-BitsTransfer], ParentContainsErrorRecordException
FullyQualifiedErrorId: PathNotFound,Microsoft.BackgroundIntelligentTransfer.Management.NewBitsTransferCommand

However if I create the folder PrerequisiteInstallerFiles and rerun the script all is fine. It creates all the folder structure except the final dir.
Is it a script issue or local issue (and if local any know solutions to this?)

//Best Regards
Patrik

**Comment by brianlala** [comment]
I'll look at this should be a simple fix.

**Comment by Patrikbrann** [comment]
Thank you Brian!
I appreciate it! 👍 

/Patrik

**Comment by brianlala** [comment]
This should now be resolved.
