### ISSUE TITLE
KB2898850 is not a prerequisite for SP2016

### ISSUE THREAD

**Issue by egor-yudkin** [brianlala/AutoSPSourceBuilder#22]
According to [Hardware and software requirements for SharePoint Server 2016](https://technet.microsoft.com/en-us/library/cc262485(v=office.16).aspx#section4) Update for Microsoft .NET Framework to disable RC4 in Transport Layer Security KB2898850 is not in the list of prerequisites, so I believe it should be removed from the AutoSPSourceBuilder.xml

**Comment by brianlala** [comment]
Correct, it's not strictly needed or used by PrerequisiteInstaller.exe, but it was mentioned in several places in the past so I left it in as a "just in case" so it would be available for manual installation for Win2012 servers etc.
