### ISSUE TITLE
Exception Calling "ReadKey" with "1" argument(s) . The method or operation is not implemented.

### ISSUE THREAD

**Issue by faisalmasood** [brianlala/AutoSPSourceBuilder#24]
Exception Calling "ReadKey" with "1" argument(s) . The method or operation is not implemented.
at ... AutoSourceSPBuilder.PS1:86 Char:9

I get the above stop error when I'm using for Sharepoint 2016 pre-Reqs only without -source switch on Windows 2016 DC Edition on HyperV 2016. I picked Jan 2018 CU update. It only downloads the first two pre-reqs and then stops.

**Comment by brianlala** [comment]
Are you by chance trying to run this in the PowerShell ISE? The Pause function uses a ReadKey method that doesn't work in the ISE.

**Comment by faisalmasood** [comment]
Yes I used PowerShell ise. In Powershell it stops after same first two downloads as well. Though it is not throwing error.

Faisal
-------- Original message --------From: Brian Lalancette <notifications@github.com> Date: 2/5/18  6:26 AM  (GMT-06:00) To: brianlala/AutoSPSourceBuilder <AutoSPSourceBuilder@noreply.github.com> Cc: faisalmasood <fm@faisalmasood.com>, Author <author@noreply.github.com> Subject: Re: [brianlala/AutoSPSourceBuilder] Exception Calling "ReadKey" with "1" argument(s) . The method or operation is not implemented. (#24) 
Are you by chance trying to run this in the PowerShell ISE? The Pause function uses a ReadKey method that doesn't work in the ISE.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/brianlala/AutoSPSourceBuilder","title":"brianlala/AutoSPSourceBuilder","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/brianlala/AutoSPSourceBuilder"}},"updates":{"snippets":[{"icon":"PERSON","message":"@brianlala in #24: Are you by chance trying to run this in the PowerShell ISE? The Pause function uses a ReadKey method that doesn't work in the ISE."}],"action":{"name":"View Issue","url":"https://github.com/brianlala/AutoSPSourceBuilder/issues/24#issuecomment-363070262"}}}

**Comment by brianlala** [comment]
OK so the ISE issue is a known one - run in a regular PS window.
But, there are only two downloads for the January 2018 PU for SharePoint 2016, what else were you looking for?

**Comment by faisalmasood** [comment]
Ok got it.

Isn't the solution suppose to download the Sharepoint 2016 Pre-Reqs as well?
https://blogit.create.pt/fabiocarvalho/2017/02/10/create-sharepoint-2016-install-package-with-autospsourcebuilder/

I'm not seeing those!

**Comment by faisalmasood** [comment]
Never mind, I got it working. I had to specify the -Source parameter with pointing to attached Sharepoint 2016 CD source. Following command worked for me.

.\UpdateSPSourceBuilder.PS1 -GetPrerequisites:$True -Source "E:\" -Destination "d:\SP\AutoSPInstaller\SP\2016"

Where E:\ is Sharepoint 2016 DVD path.

**Comment by bottlenecked** [comment]
For anyone else reading this: this also happens when using PowerShell from the VSCode console

**Comment by g17mike** [comment]
> OK so the ISE issue is a known one - run in a regular PS window.
> But, there are only two downloads for the January 2018 PU for SharePoint 2016, what else were you looking for?

Thank you so much!
