### ISSUE TITLE
hotfixv4.microsoft.com is down

### ISSUE THREAD

**Issue by andreasblueher** [brianlala/AutoSPSourceBuilder#28]
Hey Brian,

I just ran into AutoSPSourceBuilder yesterday and I really love it! Thanks for the effort and the result is stunning! I stumbled over 3 prerequisites for SP2013 which are not working because Microsoft server are down.

```
<!-- <Prerequisite Name="KB2708075 - FIX: IIS 7.5 configurations are not updated when you use the ServerManager class to commit configuration changes" Url="http://hotfixv4.microsoft.com/Windows%207/Windows%20Server2008%20R2%20SP1/sp2/Fix402568/7600/free/447698_intl_x64_zip.exe" Permalink="http://go.microsoft.com/fwlink/p/?LinkId=258851" /> -->
            <!-- <Prerequisite Name="KB2554876 - The SharePoint parsing process crashes in Windows Server 2008 R2" Url="http://hotfixv4.microsoft.com/Windows%207/Windows%20Server2008%20R2%20SP1/sp2/Fix368051/7600/free/433385_intl_x64_zip.exe" Permalink="http://go.microsoft.com/fwlink/p/?LinkId=258850" /> -->
            <!-- <Prerequisite Name="KB2472264 - You cannot customize some TCP configurations by using the netsh command in Windows Server 2008 R2" Url="http://hotfixv4.microsoft.com/Windows%207/Windows%20Server2008%20R2%20SP1/sp2/Fix354400/7600/free/427087_intl_x64_zip.exe" /> -->
```

I've search KB2708075 and came across this [link](https://www.microsoft.com/en-us/download/details.aspx?id=30235) and I'm wondering if I could use this file instead of 447698_intl_x64_zip.exe.

Regards, Andreas

**Comment by brianlala** [comment]
When you say "the servers are down" to me this sounds like a temporary thing... or do you mean the links are dead?

**Comment by andreasblueher** [comment]
I created this because I'm not sure about this. When I searched for the KB article, I couldn't find those links anymore anywhere, so one could assume that those links are old/depricated. What is your opinion on the difference in naming with the files?

**Comment by brianlala** [comment]
OK I'll verify those links now

**Comment by andreasblueher** [comment]
Thank you very much, I can confirm those links working!
