### ISSUE TITLE
SP2019 Microsoft .NET Framework 4.7.2

### ISSUE THREAD

**Issue by Laul0** [brianlala/AutoSPSourceBuilder#34]
Hi,

The Url of Microsoft .NET Framework 4.7.2 prerequisite seems to be wrong. Unable to install it directly from the script.

**Comment by brianlala** [comment]
Interesting, there was a problem with the URL; Chrome returned "ERR_INVALID_RESPONSE". Anyhow using the permalink I got the new URL: https://download.microsoft.com/download/6/E/4/6E48E8AB-DC00-419E-9704-06DD46E5F81D/NDP472-KB4054530-x86-x64-AllOS-ENU.exe. Will update the XML shortly.
