### ISSUE TITLE
No language packs for SP 2019

### ISSUE THREAD

**Issue by shurick81** [brianlala/AutoSPSourceBuilder#35]
Language URLs are missing: https://github.com/brianlala/AutoSPSourceBuilder/blob/master/AutoSPSourceBuilder.xml#L1537-L1732

URLs can be extracted here:
https://www.microsoft.com/en-us/download/details.aspx?id=57463

**Comment by zerod1ce** [comment]
Hey @shurick81 , it seems that the link / reference for the german language pack (de-de) is wrong. It downloaded the gl-es instead.
