### ISSUE TITLE
Prereqs and CU's do not download SharePoint 2019

### ISSUE THREAD

**Issue by Gberosh** [brianlala/AutoSPSourceBuilder#38]
I ran the following 
 .\AutoSPSourceBuilder.ps1 -SharePointVersion 2019 -SourceLocation E: -Destination "C:\Source\SP\2019" -GetPrerequisites $true -CumulativeUpdate "January 2019" -Languages de-de, es-es,fr-fr,it-it,ja-jp,ko-kr,nl-nl,pt-br,zh-cn,zh-tw

The screen says downloaded files but runs very quickly and then fails when trying to open the PU saying file not there.  See attached screen shot
[SP 2019 Autobuild error.docx](https://github.com/brianlala/AutoSPSourceBuilder/files/2829337/SP.2019.Autobuild.error.docx)

**Comment by brianlala** [comment]
Hi can you please make sure you have the latest version of the script by running:

`Install-Script -Name AutoSPSourceBuilder -Verbose -Force`

This will install the script to your C:\Program Files\WindowsPowerShell\Scripts folder. Then, please try again with a new PowerShell window - this time you should just be able to run the script from the above location - and please specify the -Verbose parameter as well so we get more information as to what's going on.

**Comment by Gberosh** [comment]
Yes I have the latest version. I have tried on 3 different machines all with same results.

**Comment by Gberosh** [comment]
PS C:\Program Files\WindowsPowerShell\Scripts>  .\AutoSPSourceBuilder.ps1 -SharePointVersion 2019 -SourceLocation E: -De
stination "C:\Source\SP\2019" -GetPrerequisites $true -CumulativeUpdate "January 2019" -Languages de-de, es-es,fr-fr,it-
it,ja-jp,ko-kr,nl-nl,pt-br,zh-cn,zh-tw -verbose
 -- AutoSPSourceBuilder SharePoint Update Download/Integration Utility --
 - Grabbing latest AutoSPSourceBuilder.xml patch inventory file...
VERBOSE:  - Attempting to download from
https://raw.githubusercontent.com/brianlala/AutoSPSourceBuilder/master/AutoSPSourceBuilder.xml...
VERBOSE: Importing cmdlet 'Add-BitsFile'.
VERBOSE: Importing cmdlet 'Complete-BitsTransfer'.
VERBOSE: Importing cmdlet 'Get-BitsTransfer'.
VERBOSE: Importing cmdlet 'Remove-BitsTransfer'.
VERBOSE: Importing cmdlet 'Resume-BitsTransfer'.
VERBOSE: Importing cmdlet 'Set-BitsTransfer'.
VERBOSE: Importing cmdlet 'Start-BitsTransfer'.
VERBOSE: Importing cmdlet 'Suspend-BitsTransfer'.
  - Connecting.....
  - Downloading AutoSPSourceBuilder.xml...
  - Completing transfer...
 - Done!
 - SharePoint 2019 specified on the command line.
VERBOSE: Destination is "C:\Source\SP\2019"
VERBOSE: Update location is "True"
 - Checking for E:\Setup.exe and E:\PrerequisiteInstaller.exe...
 - Source found in E:.
 - SharePoint 2019 detected.
--------------------------------------------------------------
 - (Robo-)copying files from E: to C:\Source\SP\2019\SharePoint...


------------------------------------------------------------------------------

               Total    Copied   Skipped  Mismatch    FAILED    Extras
    Dirs :        17         0        17         0         0         1
   Files :        54         0        54         0         0         0
   Bytes :   3.605 g         0   3.605 g         0         0         0
   Times :   0:00:00   0:00:00                       0:00:00   0:00:00
   Ended : Monday, February 4, 2019 12:53:29 PM

 - Done copying original files to C:\Source\SP\2019\SharePoint.
--------------------------------------------------------------
--------------------------------------------------------------
 - Getting prerequisite "Microsoft .NET Framework 4.7.2"...
 - Getting prerequisite "Microsoft SQL Server 2012 SP4 Native Client"...
 - Getting prerequisite "Microsoft Sync Framework Runtime v1.0 SP1 (x64)"...
 - Getting prerequisite "Microsoft Identity Extensions"...
 - Getting prerequisite "Microsoft Information Protection and Control Client 2.1"...
 - Getting prerequisite "Microsoft WCF Data Services 5.6"...
 - Getting prerequisite "Windows Server AppFabric"...
 - Getting prerequisite "CU Package 7 for Microsoft AppFabric 1.1 for Windows Server (KB3092423)"...
 - Getting prerequisite "Visual C++ Redistributable Package for Visual Studio 2012"...
 - Getting prerequisite "Visual C++ Redistributable Package for Visual Studio 2017"...
--------------------------------------------------------------
VERBOSE: Not processing service pack.
--------------------------------------------------------------
 - Getting SharePoint 2019 January 2019 update file (sts2019-kb4461634-fullfile-x64-glb.exe):
 - True\16.0.10340.12101 (January 2019) doesn't exist; creating...
--------------------------------------------------------------
 - Getting SharePoint 2019 January 2019 update file (wssloc2019-kb4461514-fullfile-x64-glb.exe):
 - Extracting January 2019 Public Update patch files...
  - sts2019-kb4461634-fullfile-x64-glb.exe...Start-Process : This command cannot be run due to the error: The system cannot find the file specified.
At C:\Program Files\WindowsPowerShell\Scripts\AutoSPSourceBuilder.ps1:758 char:25
+ ...             Start-Process -FilePath "$UpdateLocation\$updateSubfolder ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand

done!


 - Could not find extraction log file!
At C:\Program Files\WindowsPowerShell\Scripts\AutoSPSourceBuilder.ps1:220 char:9
+         Throw " - Could not find extraction log file!"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: ( - Could not find extraction log file!:String) [], RuntimeException
    + FullyQualifiedErrorId :  - Could not find extraction log file!

**Comment by Gberosh** [comment]
[SP 2019 Autobuild error.docx](https://github.com/brianlala/AutoSPSourceBuilder/files/2829394/SP.2019.Autobuild.error.docx)

**Comment by brianlala** [comment]
When using -GetPrerequisites try either:
`-GetPrerequisites:$true`
or, since it's now actually a switch parameter and no longer a Boolean parameter, just:
`-GetPrerequisites`

Brian

**Comment by Gberosh** [comment]
Ok simplified the command still same error 

PS C:\Program Files\WindowsPowerShell\Scripts>  .\AutoSPSourceBuilder.ps1  -SharePointVersion 2019 -SourceLocation E: -D
estination "c:\source\sp\2019" -GetPrerequisites  -CumulativeUpdate "January 2019" -verbose
 -- AutoSPSourceBuilder SharePoint Update Download/Integration Utility --
 - Grabbing latest AutoSPSourceBuilder.xml patch inventory file...
VERBOSE:  - Attempting to download from
https://raw.githubusercontent.com/brianlala/AutoSPSourceBuilder/master/AutoSPSourceBuilder.xml...
VERBOSE: Importing cmdlet 'Add-BitsFile'.
VERBOSE: Importing cmdlet 'Complete-BitsTransfer'.
VERBOSE: Importing cmdlet 'Get-BitsTransfer'.
VERBOSE: Importing cmdlet 'Remove-BitsTransfer'.
VERBOSE: Importing cmdlet 'Resume-BitsTransfer'.
VERBOSE: Importing cmdlet 'Set-BitsTransfer'.
VERBOSE: Importing cmdlet 'Start-BitsTransfer'.
VERBOSE: Importing cmdlet 'Suspend-BitsTransfer'.
  - Connecting.....
  - Downloading AutoSPSourceBuilder.xml...
  - Completing transfer...
 - Done!
 - SharePoint 2019 specified on the command line.
VERBOSE: Destination is "c:\source\sp\2019"
VERBOSE: Update location is "c:\source\sp\2019\Updates"
 - Checking for E:\Setup.exe and E:\PrerequisiteInstaller.exe...
 - Source found in E:.
 - SharePoint 2019 detected.
--------------------------------------------------------------
 - (Robo-)copying files from E: to c:\source\sp\2019\SharePoint...


------------------------------------------------------------------------------

               Total    Copied   Skipped  Mismatch    FAILED    Extras
    Dirs :        17         0        17         0         0         1
   Files :        54         0        54         0         0         0
   Bytes :   3.605 g         0   3.605 g         0         0         0
   Times :   0:00:00   0:00:00                       0:00:00   0:00:00
   Ended : Monday, February 4, 2019 1:06:14 PM

 - Done copying original files to c:\source\sp\2019\SharePoint.
--------------------------------------------------------------
 - No languages specified on the command line...
--------------------------------------------------------------
 - Getting prerequisite "Microsoft .NET Framework 4.7.2"...
 - Getting prerequisite "Microsoft SQL Server 2012 SP4 Native Client"...
 - Getting prerequisite "Microsoft Sync Framework Runtime v1.0 SP1 (x64)"...
 - Getting prerequisite "Microsoft Identity Extensions"...
 - Getting prerequisite "Microsoft Information Protection and Control Client 2.1"...
 - Getting prerequisite "Microsoft WCF Data Services 5.6"...
 - Getting prerequisite "Windows Server AppFabric"...
 - Getting prerequisite "CU Package 7 for Microsoft AppFabric 1.1 for Windows Server (KB3092423)"...
 - Getting prerequisite "Visual C++ Redistributable Package for Visual Studio 2012"...
 - Getting prerequisite "Visual C++ Redistributable Package for Visual Studio 2017"...
--------------------------------------------------------------
VERBOSE: Not processing service pack.
--------------------------------------------------------------
 - Getting SharePoint 2019 January 2019 update file (sts2019-kb4461634-fullfile-x64-glb.exe):
--------------------------------------------------------------
 - Getting SharePoint 2019 January 2019 update file (wssloc2019-kb4461514-fullfile-x64-glb.exe):
 - Extracting January 2019 Public Update patch files...
  - sts2019-kb4461634-fullfile-x64-glb.exe...Start-Process : This command cannot be run due to the error: The system cannot find the file specified.
At C:\Program Files\WindowsPowerShell\Scripts\AutoSPSourceBuilder.ps1:758 char:25
+ ...             Start-Process -FilePath "$UpdateLocation\$updateSubfolder ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand

done!


 - Could not find extraction log file!
At C:\Program Files\WindowsPowerShell\Scripts\AutoSPSourceBuilder.ps1:220 char:9
+         Throw " - Could not find extraction log file!"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: ( - Could not find extraction log file!:String) [], RuntimeException
    + FullyQualifiedErrorId :  - Could not find extraction log file!

**Comment by brianlala** [comment]
OK I'm emailing you an updated script with more verbose logging...

**Comment by Gberosh** [comment]
Same

S C:\Program Files\WindowsPowerShell\Scripts> .\AutoSPSourceBuilder.ps1 -SharePointVersion 2019 -SourceLocation E: -Destination "c:\source\sp\2019" -GetPrerequisites -CumulativeUpdate "January 2019" -verbose

Security warning
Run only scripts that you trust. While scripts from the internet can be useful, this script can potentially harm your
computer. If you trust this script, use the Unblock-File cmdlet to allow the script to run without this warning
message. Do you want to run C:\Program Files\WindowsPowerShell\Scripts\AutoSPSourceBuilder.ps1?
[D] Do not run  [R] Run once  [S] Suspend  [?] Help (default is "D"): r
 -- AutoSPSourceBuilder SharePoint Update Download/Integration Utility --
 - Grabbing latest AutoSPSourceBuilder.xml patch inventory file...
VERBOSE:  - Attempting to download from
https://raw.githubusercontent.com/brianlala/AutoSPSourceBuilder/master/AutoSPSourceBuilder.xml...
VERBOSE: Loading module from path 'C:\Windows\system32\WindowsPowerShell\v1.0\Modules\BitsTransfer\BitsTransfer.psd1'.
VERBOSE: Loading 'Assembly' from path
'C:\Windows\system32\WindowsPowerShell\v1.0\Modules\BitsTransfer\Microsoft.BackgroundIntelligentTransfer.Management.Int
erop.dll'.
VERBOSE: Loading 'Assembly' from path
'C:\Windows\system32\WindowsPowerShell\v1.0\Modules\BitsTransfer\Microsoft.BackgroundIntelligentTransfer.Management.Int
erop.dll'.
VERBOSE: Loading 'FormatsToProcess' from path
'C:\Windows\system32\WindowsPowerShell\v1.0\Modules\BitsTransfer\BitsTransfer.Format.ps1xml'.
VERBOSE: Exporting cmdlet 'Add-BitsFile'.
VERBOSE: Exporting cmdlet 'Remove-BitsTransfer'.
VERBOSE: Exporting cmdlet 'Complete-BitsTransfer'.
VERBOSE: Exporting cmdlet 'Get-BitsTransfer'.
VERBOSE: Exporting cmdlet 'Start-BitsTransfer'.
VERBOSE: Exporting cmdlet 'Resume-BitsTransfer'.
VERBOSE: Exporting cmdlet 'Set-BitsTransfer'.
VERBOSE: Exporting cmdlet 'Suspend-BitsTransfer'.
VERBOSE: Importing cmdlet 'Add-BitsFile'.
VERBOSE: Importing cmdlet 'Complete-BitsTransfer'.
VERBOSE: Importing cmdlet 'Get-BitsTransfer'.
VERBOSE: Importing cmdlet 'Remove-BitsTransfer'.
VERBOSE: Importing cmdlet 'Resume-BitsTransfer'.
VERBOSE: Importing cmdlet 'Set-BitsTransfer'.
VERBOSE: Importing cmdlet 'Start-BitsTransfer'.
VERBOSE: Importing cmdlet 'Suspend-BitsTransfer'.
  - Connecting.....
  - Downloading AutoSPSourceBuilder.xml...
  - Completing transfer...
 - Done!
 - SharePoint 2019 specified on the command line.
VERBOSE: Destination is "c:\source\sp\2019"
VERBOSE: Update location is "c:\source\sp\2019\Updates"
 - Checking for E:\Setup.exe and E:\PrerequisiteInstaller.exe...
 - Source found in E:.
 - SharePoint 2019 detected.
--------------------------------------------------------------
 - (Robo-)copying files from E: to c:\source\sp\2019\SharePoint...


------------------------------------------------------------------------------

               Total    Copied   Skipped  Mismatch    FAILED    Extras
    Dirs :        17         0        17         0         0         1
   Files :        54         0        54         0         0         0
   Bytes :   3.605 g         0   3.605 g         0         0         0
   Times :   0:00:00   0:00:00                       0:00:00   0:00:00
   Ended : Monday, February 4, 2019 2:33:14 PM

 - Done copying original files to c:\source\sp\2019\SharePoint.
--------------------------------------------------------------
 - No languages specified on the command line...
--------------------------------------------------------------
 - Getting prerequisite "Microsoft .NET Framework 4.7.2"...
 - Getting prerequisite "Microsoft SQL Server 2012 SP4 Native Client"...
 - Getting prerequisite "Microsoft Sync Framework Runtime v1.0 SP1 (x64)"...
 - Getting prerequisite "Microsoft Identity Extensions"...
 - Getting prerequisite "Microsoft Information Protection and Control Client 2.1"...
 - Getting prerequisite "Microsoft WCF Data Services 5.6"...
 - Getting prerequisite "Windows Server AppFabric"...
 - Getting prerequisite "CU Package 7 for Microsoft AppFabric 1.1 for Windows Server (KB3092423)"...
 - Getting prerequisite "Visual C++ Redistributable Package for Visual Studio 2012"...
 - Getting prerequisite "Visual C++ Redistributable Package for Visual Studio 2017"...
--------------------------------------------------------------
VERBOSE: Not processing service pack.
--------------------------------------------------------------
 - Getting SharePoint 2019 January 2019 update file (sts2019-kb4461634-fullfile-x64-glb.exe):
--------------------------------------------------------------
 - Getting SharePoint 2019 January 2019 update file (wssloc2019-kb4461514-fullfile-x64-glb.exe):
 - Extracting January 2019 Public Update patch files...
  - sts2019-kb4461634-fullfile-x64-glb.exe...VERBOSE:   - Extracting from 'c:\source\sp\2019\Updates\16.0.10340.12101 (January
2019)\sts2019-kb4461634-fullfile-x64-glb.exe'
Start-Process : This command cannot be run due to the error: The system cannot find the file specified.
At C:\Program Files\WindowsPowerShell\Scripts\AutoSPSourceBuilder.ps1:761 char:25
+ ...             Start-Process -FilePath "$UpdateLocation\$updateSubfolder ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand

done!


 - Could not find extraction log file!
At C:\Program Files\WindowsPowerShell\Scripts\AutoSPSourceBuilder.ps1:220 char:9
+         Throw " - Could not find extraction log file!"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: ( - Could not find extraction log file!:String) [], RuntimeException
    + FullyQualifiedErrorId :  - Could not find extraction log file!

**Comment by brianlala** [comment]
Thanks for the additional info. I can now see that the file we're trying to extract from is:
`c:\source\sp\2019\Updates\16.0.10340.12101 (January 2019)\sts2019-kb4461634-fullfile-x64-glb.exe`

What happens if you try to run that file path (e.g. using Start-->Run or within the same PowerShell window)?

**Comment by Gberosh** [comment]
The folder location is empty the same is true for the prereq's folder

[SP 2019 Autobuild error.docx](https://github.com/brianlala/AutoSPSourceBuilder/files/2829779/SP.2019.Autobuild.error.docx)

**Comment by brianlala** [comment]
Interesting, seems none of the files are being downloaded for you. Can you check if the BITS (Background Intelligent File Transfer) service is running on this machine? Do you see any progress indicated on the screen while the file downloads are happening?

**Comment by Gberosh** [comment]
No there was no progress indicator..  The service was not running I started and same results files are not downloading.  Do I need to restart the server after starting the service?

**Comment by brianlala** [comment]
I'm pretty sure you wouldn't have to restart the server, but is there another machine/workstation you can try running the script on?

**Comment by Gberosh** [comment]
ok verified service is running on 2 different machines..still no files are downloaded.  Is there a small ps I can test with to have it try one file

**Comment by brianlala** [comment]
Sure, try this:

`Start-BitsTransfer -Destination c:\temp\VC_redist.x64.exe -Source https://download.visualstudio.microsoft.com/download/pr/11687625/2cd2dba5748dc95950a5c42c2d2d78e4/VC_redist.x64.exe -Priority Foreground -Verbose`

Then check the C:\Temp folder afterwards. Note, you might have to create this folder first.

**Comment by Gberosh** [comment]
File downloaded to the C:\temp folder. I saw a download progress bar pop open at top of powershell window too

**Comment by brianlala** [comment]
I just reproduced this problem locally. Something buggy about the last commit, stay tuned.

**Comment by brianlala** [comment]
OK - just published the fixed script. Grab the new one again using:
`Install-Script -Name AutoSPSourceBuilder -Verbose -Force`
and try to run the same command line as you were trying earlier.

**Comment by Gberosh** [comment]
That did the trick!!!  **### Thank you very much** for looking into the issue.

**Comment by brianlala** [comment]
No, thank you for raising what was a totally valid issue. Was a dumb mistake that I should have caught in testing :)

Cheers
