### ISSUE TITLE
Distribution via PS Gallery

### ISSUE THREAD

**Issue by shurick81** [brianlala/AutoSPSourceBuilder#39]
As a DevOps I want to be able to install and update AutoSPSourceBuilder as a PS module

**Comment by brianlala** [comment]
It's already there!

`Install-Script -Name AutoSPSourceBuilder`

**Comment by shurick81** [comment]
Wonderful! Is it something worth mentioning in documentation?

**Comment by brianlala** [comment]
Lol there's documentation? I have already modified the description on the main project with mention of the gallery, where else do you think it would make sense?
