### ISSUE TITLE
MSODBCSQL.msi Download Error

### ISSUE THREAD

**Issue by airdouglas** [brianlala/AutoSPSourceBuilder#4]
It would appear that there is an error in the path for the MSODBCSQL.msi pre-requisite for SharePoint 2016.  The xml file specifies the following:

http://download.microsoft.com/download/5/7/2/57249A3A-19D6-4901-ACCE-80924ABEB267/1033/x64/msodbcsql.msi

Microsoft must have moved the download to:

http://download.microsoft.com/download/5/7/2/57249A3A-19D6-4901-ACCE-80924ABEB267/1033/amd64/msodbcsql.msi

We were getting an error trying to download using the original link.

**Comment by walkercz** [comment]
already mentioned in #2 pull request

**Comment by brianlala** [comment]
Sorry folks, totally missed this one prior to now. The download link has indeed changed and I will be updating it shortly.

Brian

**Comment by Jecornille** [comment]
The download link has changed again. I tried today, and the link is now https://download.microsoft.com/download/5/7/2/57249A3A-19D6-4901-ACCE-80924ABEB267/ENU/x64/msodbcsql.msi

**Comment by brianlala** [comment]
Confirmed. I'll update it shortly - thanks!
