### ISSUE TITLE
Optionally remove features that prevents running in CI

### ISSUE THREAD

**Issue by shurick81** [brianlala/AutoSPSourceBuilder#40]
As a DevOps i want to be able to prepare slipstreamed media in pipeline, but some features prevent to run it. For example, `$Host.UI.RawUI.WindowTitle = " -- AutoSPSourceBuilder --"` is probably something to get rid of.

**Comment by brianlala** [comment]
If you happen to know what we could check for to determine if we're running in that mode, it would be easy to incorporate while still allowing for useful display info when we're running interactively.

**Comment by shurick81** [comment]
For example, $Host.UI.RawUI.WindowTitle = " -- AutoSPSourceBuilder --" is probably something to get rid of.

**Comment by shurick81** [comment]
I think we can introduce some switch, like "Unattend" and then conditionally remove these CLI beauty, like this WindowTitle and also like "Pause" function that is expecting some input from user

**Comment by shurick81** [comment]
This commit looks good, I tried it with SP 2016 and 2019, worked just fine.
