### ISSUE TITLE
hotfixv4 doesn't return 447698_intl_x64_zip anymore

### ISSUE THREAD

**Issue by andreasblueher** [brianlala/AutoSPSourceBuilder#41]
Hey Brian,

when trying to create a new source for SP2013 I ran into the following issue.
![image](https://user-images.githubusercontent.com/12544512/53743974-4251fb00-3e9c-11e9-8ad7-19707b948e21.png)

I'm not sure if it's temporary or permanent, will try again later this week and come back here.

**Comment by brianlala** [comment]
Right, looks like the hotfix is no longer available:
![image](https://user-images.githubusercontent.com/12145177/54028018-87fb1600-4171-11e9-8ba0-a97d867e5701.png)
I'll comment it out of the XML then since it seems like it's no longer required or applicable.

**Comment by andreasblueher** [comment]
I think this issue can be closed than. Thank!
