### ISSUE TITLE
SharePoint 2016: Fixed version of February 2019 CU (STS)

### ISSUE THREAD

**Issue by gszdev** [brianlala/AutoSPSourceBuilder#42]
Maybe you should replace or update the February CU for SharePoint 2016
Have a look at:
[A fix for the regression in February 2019 CU for SP2016 has been released today](https://blogs.technet.microsoft.com/stefan_gossner/2019/02/27/a-fix-for-the-regression-in-february-2019-cu-for-sp2016-has-been-released-today/)

Replace STS Update for SP2016 (line 1113) of AutoSPSourceBuilder.xml
 with the following (sts2016-kb3085363-fullfile-x64-glb.exe version 16.0.4810.100**1**)

`<CumulativeUpdate Name="February 2019" Build="16.0.4810.1001" Url="https://download.microsoft.com/download/6/5/5/655CE976-72C5-49E8-A8BF-38FE2C93192E/sts2016-kb3085363-fullfile-x64-glb.exe" ExpandedFile="sts2016-kb3085363-fullfile-x64-glb.exe" />`

**Comment by brianlala** [comment]
Done - thanks for the tip about the update link!
