### ISSUE TITLE
de-de Language Pack in Autospinstaller

### ISSUE THREAD

**Issue by kopfnicka** [brianlala/AutoSPSourceBuilder#48]
hello,
greate project, love it !!

but one thing, the autospsourcebuilder downloads the wrong languagepack for de-de.
you'll receive the gl-es language pack because the link in the autospsourcebuilder.xml targets to the wrong source -  could you please correct this so de-de will be downloaded ?

cheers
kopfnicka

**Comment by brianlala** [comment]
Thanks for the feedback, please submit a PR with your proposed changes and I'll review!

**Comment by kopfnicka** [comment]
Hello,

After executing the following command with parameter Languages “de-de” the
wrong language pack namely the gl-es Languagepack will be downloaded.

Command: .\AutoSPSourceBuilder.ps1 -SourceLocation E: -Destination
"D:\SP2019" -GetPrerequisites $true -SharePointVersion “2019” -Languages
“de-de”

the same happens when i use parameter: PromptForLanguages and choose de-de
the gl-es will be downloaeded.

This is because the url in the xml for de-de ist the one of gl-es:
<LanguagePack Name="gl-es" Url="
https://download.microsoft.com/download/3/7/A/37A556F1-4500-459F-9537-8728C073A80B/serverlanguagepack.exe
">
<LanguagePack Name="de-de" Url="
https://download.microsoft.com/download/3/7/A/37A556F1-4500-459F-9537-8728C073A80B/serverlanguagepack.exe
">
<LanguagePack Name="gl-es" Url="
https://download.microsoft.com/download/3/7/A/37A556F1-4500-459F-9537-8728C073A80B/serverlanguagepack.exe
">
<LanguagePack Name="de-de" Url="
https://download.microsoft.com/download/3/7/A/37A556F1-4500-459F-9537-8728C073A80B/serverlanguagepack.exe
">

it unfortunately doesnt help changing the url in the
AutoSpSourceBuilder.xml.

cheers
Christoph!

Am Di., 28. Mai 2019 um 16:18 Uhr schrieb Brian Lalancette <
notifications@github.com>:

**Comment by uelikuratli** [comment]
Same here, please fix the url in the xml, you can use the parameter -UseExistingLocalXML so chaning the url in the xml will work.

**Comment by andreasblueher** [comment]
This can be closed.
