### ISSUE TITLE
Incorrect Update Listed for Dec 2019

### ISSUE THREAD

**Issue by Getoffmypatch** [brianlala/AutoSPSourceBuilder#59]
The SP 2019 update from December is incorrect.

The sts should be "sts2019-kb4484177-fullfile-x64-glb.exe"
https://www.microsoft.com/en-us/download/confirmation.aspx?id=100693
The one listed is the Jan update.

Also the wssloc is incorrect as it lists the Nov update.
It should be "wssloc2019-kb4484176-fullfile-x64-glb.exe"
https://www.microsoft.com/en-us/download/details.aspx?id=100733
The one listed is from Nov

**Comment by brianlala** [comment]
Wow yeah I made quite a mess there... anyhow it will all be fixed shortly!
