### ISSUE TITLE
An error occurred downloading svrsetup_15-0-4709-1000_x64.zip

### ISSUE THREAD

**Issue by shurick81** [brianlala/AutoSPSourceBuilder#69]
Using `-GetPrerequisites` switch with SP 2013 gives the following error:

```
- An error occurred downloading svrsetup_15-0-4709-1000_x64.zip, retrying...
```

I think it is because https://download.microsoft.com/download/3/6/2/362C4A9C-4AFE-425E-825F-369D34D64F4E/svrsetup_15-0-4709-1000_x64.zip is no longer available.

**Comment by andreasblueher** [comment]
It is available for me now. Can this be closed?
