### ISSUE TITLE
August 2020 PU Missing

### ISSUE THREAD

**Issue by Getoffmypatch** [brianlala/AutoSPSourceBuilder#72]
Hi Brian,

Do you have a timeline for adding Aug PU?

KB4484472
https://www.microsoft.com/en-us/download/details.aspx?id=101715
sts2019-kb4484472-fullfile-x64-glb.exe

KB4484471
https://www.microsoft.com/en-us/download/details.aspx?id=101713
wssloc2019-kb4484471-fullfile-x64-glb.exe

Thanks,
Shane

**Comment by brianlala** [comment]
Sorry been lazy this month... look for them soon!
