### ISSUE TITLE
October PU missing

### ISSUE THREAD

**Issue by Charansai1004** [brianlala/AutoSPSourceBuilder#75]
Hi Brian,

Do you have a timeline for adding Oct PU?

https://support.microsoft.com/en-us/help/4486676/security-update-for-sharepoint-server-2019-october-13-2020

https://support.microsoft.com/en-us/help/4486675/october-13-2020-update-for-sharepoint-server-2019-language-pack-kb4486 

Regards,
Charan

**Comment by brianlala** [comment]
Just added.
