### ISSUE TITLE
SQL 2012 native client has moved

### ISSUE THREAD

**Issue by shurick81** [brianlala/AutoSPSourceBuilder#76]
http://download.microsoft.com/download/4/B/1/4B1E9B0E-A4F3-4715-B417-31C82302A70A/ENU/x64/sqlncli.msi URL is no longer available. Should we use SQL 2012 SP4 Native Client as a prerequisite for SP 2016 (similarly to how SP 2019 is using it)? I have tried it and it worked perfectly but I'm not sure it is fully supported by MS. The alternative might be installing "SQL Server® 2012 Native Client - QFE". I haven't really tried it.

Either way, should we update the AutoSPSourceBuilder?

**Comment by brianlala** [comment]
Thanks for raising this. Let me bring it up internally and see what the official guidance is. Stay tuned!

Brian

**Comment by centuryx476** [comment]
Hello,
Can I download manually the sqlncli.msi and drop it into the "PrerequisiteInstallerFiles" folder ?
This Link: https://www.microsoft.com/en-us/download/details.aspx?id=56833

**Comment by brianlala** [comment]
I wonder what the prerequisiteinstaller.exe would use for SP2016 in this case, if we let it run in online mode? If one of us gets the chance we should run it and then check the log for the permalink...

**Comment by shurick81** [comment]
That's how I found it. It fails with 1620 exit code. I have attached an issue from SharePointDsc above also.

**Comment by brianlala** [comment]
Have reach out to the product group internally, stay tuned.

**Comment by brianlala** [comment]
So per Yorick's comments and PR over at SharePointDSC, I have updated the URL for the SQL Server 2012 Native Client. Hopefully they update the permalink soon too, so manual installs work.

**Comment by brianlala** [comment]
Permalink/FWLINK has been updated by the PG! New destination URL is the same as the one for SP2019: https://download.microsoft.com/download/F/3/C/F3C64941-22A0-47E9-BC9B-1A19B4CA3E88/ENU/x64/sqlncli.msi
