### ISSUE TITLE
"Microsoft Sync Framework Runtime v1.0 SP1 (x64)" link broken

### ISSUE THREAD

**Issue by shurick81** [brianlala/AutoSPSourceBuilder#88]
Probably the resource was deleted by Microsoft.

The URL http://go.microsoft.com/fwlink/p/?LinkID=224449 redirects to https://go.microsoft.com/fwlink/p/?LinkID=224449, which in it's turn redirects to https://download.microsoft.com/download/E/0/0/E0060D8F-2354-4871-9596-DC78538799CC/Synchronization.msi but this one returns 404.

**Comment by gszdev** [comment]
Hi @shurick81,
Here's a workaround till the some finds a direct link to the Synchronization.msi file.
Download the **SyncSetup_en.x64.zip** from the following link and extract it. You can find the msi file in the folder "Microsoft Sync Framework".
[Microsoft Sync Framework 1.0 SP1](https://www.microsoft.com/en-us/download/details.aspx?id=17616)

**Comment by shurick81** [comment]
Now the link seems working again
