### ISSUE TITLE
October 2016 CU for SharePoint 2016

### ISSUE THREAD

**Issue by ErikBoSo** [brianlala/AutoSPSourceBuilder#9]
Please add:
`<CumulativeUpdate Name="October 2016" Url="https://download.microsoft.com/download/A/4/6/A464472A-68B0-41FB-A2EA-17F0F215142A/sts2016-kb3118372-fullfile-x64-glb.exe" Build="16.0.4444.1000" ExpandedFile="sts2016-kb3118372-fullfile-x64-glb.exe"/>
`
to `<Products><Product Name="SP2016"><CumulativeUpdates>`.

**Comment by brianlala** [comment]
Done.
