### ISSUE TITLE
Missing August 2021 CU in autospsourcebuilder.xml

### ISSUE THREAD

**Issue by SPDEVGUY** [brianlala/AutoSPSourceBuilder#91]
Missing these for SP 2019.

            <CumulativeUpdate Name="August 2021" Build="16.0.10377.20001" Url="https://download.microsoft.com/download/a/4/1/a41f9823-b8fd-4e67-aff7-6532e0d67c9d/sts2019-kb5002000-fullfile-x64-glb.exe" ExpandedFile="sts2019-kb5002000-fullfile-x64-glb.exe" />
            <CumulativeUpdate Name="August 2021" Build="16.0.10377.20001" Url="https://download.microsoft.com/download/6/7/7/6776e5a8-6634-459c-961d-f9cb4f0c8d91/wssloc2019-kb5002001-fullfile-x64-glb.exe" ExpandedFile="wssloc2019-kb5002001-fullfile-x64-glb.exe" />

The script will just redownload the one on the git repo and nukes the lines I added, so you'll need to update your repository with the latest CU's since June plz thx love you <3

**Comment by brianlala** [comment]
I'm not always able to update the XML as the new updates are released, but you're free to submit a PR with your changes if you get to it first. August updates are in there now.
